#pragma once

#define IDR_SFX_DARKSOULS       "NXA_SFX_DARKSOULS"
#define IDB_TEX_DARKSOULS_EN    "NXA_TEX_DARKSOULS_EN"
#define IDB_TEX_DARKSOULS_DE    "NXA_TEX_DARKSOULS_DE"
#define IDB_TEX_DARKSOULS_ES    "NXA_TEX_DARKSOULS_ES"
#define IDB_TEX_DARKSOULS_FR    "NXA_TEX_DARKSOULS_FR"

#define IDR_SFX_ANGRYPEPE       "NXA_SFX_ANGRYPEPE"
#define IDB_TEX_ANGRYPEPE       "NXA_TEX_ANGRYPEPE"

#define IDR_SFX_GTA             "NXA_SFX_GTA"
#define IDB_TEX_GTA_EN          "NXA_TEX_GTA_EN"
#define IDB_TEX_GTA_DE          "NXA_TEX_GTA_DE"
#define IDB_TEX_GTA_ES          "NXA_TEX_GTA_ES"
#define IDB_TEX_GTA_FR          "NXA_TEX_GTA_FR"
#define IDB_TEX_GTA_PHOTO       "NXA_TEX_GTA_PHOTO"
#define IDB_TEX_GTA_FLASH       "NXA_TEX_GTA_FLASH"

#define IDR_SFX_RYTLOCK         "NXA_SFX_RYTLOCK"
#define IDB_TEX_RYTLOCK_0       "NXA_TEX_RYTLOCK_0"
#define IDB_TEX_RYTLOCK_1       "NXA_TEX_RYTLOCK_1"
#define IDB_TEX_RYTLOCK_2       "NXA_TEX_RYTLOCK_2"
#define IDB_TEX_RYTLOCK_3       "NXA_TEX_RYTLOCK_3"
#define IDB_TEX_RYTLOCK_4       "NXA_TEX_RYTLOCK_4"
#define IDB_TEX_RYTLOCK_5       "NXA_TEX_RYTLOCK_5"

#define IDR_SFX_SEKIRO          "NXA_SFX_SEKIRO"
#define IDB_TEX_SEKIRO          "NXA_TEX_SEKIRO"
#define IDB_TEX_SEKIRO_OUT      "NXA_TEX_SEKIRO_OUT"

#define IDR_SFX_WINXP           "NXA_SFX_WINXP"
#define IDB_TEX_WINXP           "NXA_TEX_WINXP"

#define IDR_FONT_ATHELAS        "NXA_FONT_ATHELAS"
#define IDR_FONT_CONSOLA        "NXA_FONT_CONSOLA"

#define IDR_DATA_LOCALIZATION   "NXA_DATA_LOCALIZATION"
